#!/usr/bin/env python3
"""Generate mediamtx.yml paths from config.yml (optional restream mode)."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

import yaml

_ENV_PATTERN = re.compile(r"\$\{([A-Za-z0-9_]+)\}")


def _expand_env(s: str) -> str:
    def repl(m: re.Match[str]) -> str:
        key = m.group(1)
        if key not in os.environ:
            raise SystemExit(f"Missing environment variable {key} for RTSP URL expansion")
        return os.environ[key]

    return _ENV_PATTERN.sub(repl, s)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--config", default="config.yml")
    p.add_argument("--output", default="mediamtx.generated.yml")
    args = p.parse_args()
    cfg_path = Path(args.config)
    if not cfg_path.is_file():
        print(f"Missing {cfg_path}", file=sys.stderr)
        raise SystemExit(2)
    raw = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    cams = raw.get("cameras") or []
    lines = [
        "# Generated by scripts/generate_mediamtx_config.py — review before use.",
        "logLevel: info",
        "rtsp: yes",
        "paths:",
    ]
    for c in cams:
        cid = c.get("id")
        src = c.get("rtsp_url")
        if not cid or not src:
            continue
        expanded = _expand_env(str(src)) if "${" in str(src) else str(src)
        lines.append(f"  {cid}:")
        lines.append(f"    source: {expanded}")
    out = Path(args.output)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
